"""empty message

Revision ID: 1da195d055c0
Revises: None
Create Date: 2014-10-15 04:33:22.378903

"""

# revision identifiers, used by Alembic.
revision = '1da195d055c0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
